version: '3.9'
services:
  backend:
    depends_on:
      - redis
    build: ./apps/backend
    ports:
      - 3001:3001
  redis:
    image: redis:7.0.11-alpine
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
    restart: always
  nginx:
    depends_on:
      - backend
      - uptime-kuma
    image: nginx:1.23.4-alpine
    ports:
      - 80:80
    volumes:
      - ./apps/nginx/nginx.conf:/etc/nginx/nginx.conf
  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - ./data/uptime-kuma:/app/data
    ports:
      - 3002:3001
    restart: always
