version: '3.9'
services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data/nginx-proxy-manager:/data
      - ./data/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - shared

networks:
  shared:
    name: shared
