# nginx-proxy-manager: Port 80, 81, 443  - ./data/nginx-proxy-manager
# backend-api:         Port 5000         -
# uptime-kuma:         Port 5001         - ./data/uptime-kuma
# redis:               Port 6379         - ./data/redis

version: '3.9'
services:
  backend:
    depends_on:
      - redis
    build: ./apps/backend
    ports:
      - 5000:3001
  redis:
    image: redis:7.0.11-alpine
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
    restart: always
  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - ./data/uptime-kuma:/app/data
    ports:
      - 5001:3001
    restart: always
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data/nginx-proxy-manager:/data
      - ./data/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
